### PR TITLE
Last minute tweaks

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@nmegill - look okay?

**Comment by nmegill** [comment]
Could you change "the previous formally published edition" to the "the previous edition formally published in 2005"?  That way they can look at the notes since 2005 to see what's changed in the printed book.

**Comment by nmegill** [comment]
Oops, not 2005, should be 2007.

**Comment by david-a-wheeler** [comment]
2005, got it.

**Comment by david-a-wheeler** [comment]
Er, 2007, got it.

**Comment by david-a-wheeler** [comment]
@nmegill - done!  If okay, please merge.  And... are we done?

**Comment by nmegill** [comment]
> 2005, got it.

Now I'm confused.  The Metamath home page says 2007 twice.

Under product details, lulu.com says:
ISBN 9781411637245 
Published  July 25, 2008 

If I look for the ISBN on Amazon, it says 2005.  The "Note Added June 22, 2005" in the Preface makes me think that I first published it shortly after that date.

I recall updating the book once on Lulu (without changing the ISBN). I think that was in 2007, because that date is on the MM home page.  This wasn't really a new edition but just a "2nd printing".  Later, perhaps in 2008, Lulu said the cover font size was messed up due to some new software on their site wizard and asked me to correct it, which I did; that may have triggered the 2008 publish date that they are listing.

Perhaps we should use 2005 - I think most books use the original publishing date for bibliographies and not one of perhaps numerous later "printings" that may correct minor typos.

**Comment by nmegill** [comment]
I'm going to leave it at 2007, because that's what people have been using from the bibtex entry I provided.  So we're done.

**Pull request merged**
