### PR TITLE
Update MM commands in "Exploring the Set Theory Database"

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Benoît Jubin said:

> 105: update outputs of MM> show statement prth/full and
> MM> show proof prth/essential/lemmon/renumber (and probably others)

This commit updates all the MM output in this section,
including changes to step numbers where needed.

I also modified the text; "show proof" only shows the essential
steps by default, and the text needed an update to match.

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by benjub** [comment]
@david-a-wheeler In the book, I found two "permissable" which should be
"permissible", as well as "worst that will happen" which, I think, should
be replaced by "worst that could happen".
Sorry for the unusual place to report this: I don't have access to my
github identifiers here.  Also, I've seen these typos in the version that
is currently on us2.metamath.org; sorry if they are already corrected.

**Comment by nmegill** [comment]
@david-a-wheeler I'll wait until you address @benjub's comment.

**Comment by david-a-wheeler** [comment]
@nmegill - addressed!

**Comment by nmegill** [comment]
@david-a-wheeler This PR has a Travis failure.

**Pull request merged**
