### PR TITLE
Update textual description of axioms

### PR DESCRIPTION
**Pull request by david-a-wheeler**
Update the text describing the axioms so that it starts to
match the actual axioms :-).

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@nmegill - does this make sense?

**Comment by nmegill** [comment]
Some double quotes need to be changed to paired single quotes, "xxx" -> \`\`xxx''.

Otherwise it is ok for now and can be merged. 

Later we might want to explain more clearly the terms "scheme" and "metavariable".

And perhaps a simple example showing the notions of "free variable" and "proper substitution"?  (We mention these terms but give the reader no idea what they mean.  OTOH we don't want to get involved with explaining them in detail since they are ultimately not directly relevant.)

**Comment by nmegill** [comment]
Assuming the reader knows some high-school calculus (hopefully a safe assumption), one possible example is "integral from 0 to x of x dx" (in standard textbook symbols) where x is both free and bound, and proper substitution of y for x would be "integral from 0 to y of x d x" where we change only the free occurrence of x to become y.

**Comment by david-a-wheeler** [comment]
Let's make these separate issues:

* Later we might want to explain more clearly the terms "scheme" and "metavariable".
* And perhaps a simple example showing the notions of "free variable" and "proper substitution"?

I prefer working small steps at a time when I can.

**Pull request merged**
