### PR TITLE
Clarify df-sb

### PR DESCRIPTION
**Pull request by david-a-wheeler**
There are many ways to express substitution.  Note several of them,
and also provide a simple mental trick to help remember what
the df-sb notation means.

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Comment by benjub** [comment]
You wrote "This also be".

**Comment by nmegill** [comment]
@david-a-wheeler I'll merge after you fix the typo noted by @benjub

**Comment by david-a-wheeler** [comment]
Well, it certainly also be :-).  Fixing now!

**Comment by david-a-wheeler** [comment]
@nmegill - I think the typo be fixed now :-).

**Pull request merged**
